
// This file is automatically generated. Do not edit it directly.
console.log("SUPABASE INIT", SUPABASE_URL);
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iosyxgmsjxlrzauwplm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_gt0nIZdbvzfmn0jb4J-V3A_xuxSR4j9";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
