// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubzqdcqojbqrucmvmkug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVienFkY3FvamJxcnVjbXZta3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjU2NjksImV4cCI6MjA2MDkwMTY2OX0.b8-mYYcCKXKCBIQ8uJGp2D1IwSIYhNS5jYNktI52URk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);